# Generated by Django 5.2.13 on 2026-04-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('world', models.CharField(choices=[('forest', 'Forest of Numbers'), ('bridge', 'Bridge of Addition'), ('cave', 'Cave of Multiplication'), ('castle', 'Castle of Equations'), ('island', 'Treasure Island')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('unlock_order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['unlock_order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction'), ('multiplication', 'Multiplication'), ('division', 'Division')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('question_text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=50)),
                ('option_b', models.CharField(max_length=50)),
                ('option_c', models.CharField(max_length=50)),
                ('option_d', models.CharField(max_length=50)),
                ('correct_answer', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('wrong_answers', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='users.userprofile')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='game.level')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obstacle_type', models.CharField(choices=[('treasure_chest', 'Treasure Chest'), ('bridge', 'Bridge'), ('gate', 'Gate'), ('rock', 'Rock'), ('magical_door', 'Magical Door')], max_length=30)),
                ('obstacle_name', models.CharField(max_length=120)),
                ('sequence_order', models.PositiveIntegerField()),
                ('required_questions', models.PositiveIntegerField(default=1)),
                ('reward_points', models.PositiveIntegerField(default=10)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obstacles', to='game.level')),
            ],
            options={
                'ordering': ['sequence_order'],
                'unique_together': {('level', 'sequence_order')},
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('obstacle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='game.obstacle')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='game.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='game.gamesession')),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
    ]
