# Generated by Django 5.2.13 on 2026-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='obstacle_type',
            field=models.CharField(choices=[('treasure_chest', 'Treasure Chest'), ('bridge', 'Bridge'), ('gate', 'Gate'), ('rock', 'Rock'), ('magical_door', 'Magical Door'), ('mini_boss', 'Mini Boss')], max_length=30),
        ),
    ]
