# Generated by Django 5.2.13 on 2026-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='last_played_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statistics',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
